name: Github Actions
on:
  push:
    branches:
      - master

jobs:
  build_windows:
    name: libwinmedia
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cmake .
      - run: cmake --build . --config Release
      - uses: actions/upload-artifact@v1
        with:
          name: libwinmedia
          path: Release
