name: Github Actions
on:
  push:
    branches:
      - master

jobs:
  build_windows:
    name: libwinmedia Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cmake .
      - run: cmake --build . --config Release
      - uses: actions/upload-artifact@v1
        with:
          name: libwinmedia-windows-core
          path: Release
      - run: del CMakeCache.txt
      - run: cmake -DDART_VM=Enable .
      - run: cmake --build . --config Release
      - uses: actions/upload-artifact@v1
        with:
          name: libwinmedia-windows-dart-vm
          path: Release

  build_linux:
    name: libwinmedia Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update
      - run: sudo apt-get install libwebkit2gtk-4.0-dev
      - run: cmake .
      - run: cmake --build . --config Release
      - uses: actions/upload-artifact@v1
        with:
          name: libwinmedia-linux-core
          path: libwinmedia.so
      - run: rm CMakeCache.txt
      - run: cmake -DDART_VM=Enable .
      - run: cmake --build . --config Release
      - uses: actions/upload-artifact@v1
        with:
          name: libwinmedia-linux-dart-vm
          path: libwinmedia.so
